name: calculate code-coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install --user .
    - name: Test coverage with pytest
      run: |
        TESTCOV="$(pytest --cov=. --cov-report=term | grep TOTAL | awk {'print $4'})"
        TOKENS=($TESTCOV)
        echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
        REF=${{ github.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        # var BRANCH_NAME = PATHS[1] + PATHS[2];
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        # process.env.BRANCH = 'pull_27';
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
    - name: Create Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{secrets.GIST_SECRET }}
        gistID: 2c51ac403e7cee714b127c1b33a1d8d1
        filename: iact_observation_planner__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
        namedLogo: pytest



        
